import { NestFactory } from "@nestjs/core";
import { DocumentBuilder, SwaggerModule } from "@nestjs/swagger";
import metadata from "./metadata"; // <-- file auto-generated by the "PluginMetadataGenerator"

import { AppModule } from "./app.module";

async function bootstrap() {
	const app = await NestFactory.create(AppModule);

	await SwaggerModule.loadPluginMetadata(metadata); // <-- here
	const config = new DocumentBuilder()
		.setTitle("StartupSphere API")
		.setDescription(
			"API documentation for StartupSphere, the 3D mapping platform for startup ecosystems."
		)
		.setVersion("1.0")
		.build();
	const document = SwaggerModule.createDocument(app, config);
	SwaggerModule.setup("docs", app, document);

	await app.listen(3000);
}
bootstrap();
